name: Download Dependencies

on:
  schedule:
      # 6am UTC is 7am Central European Time (CET) or 8am Central European Summer Time (CEST).
    - cron: '0 5 * * SAT'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Get current date
      id: date
      run: echo "today=$(date +'%Y-%m-%d')" > $GITHUB_OUTPUT

    - name: Cache GCC Binaries
      id: cache-gcc
      uses: actions/cache@v4
      env:
          cache-name: cache-gcc-binaries
      with:
          path: ./Toolchain
          key: gcc-binaries-${{ steps.date.outputs.date }}



    - name: Download GCC Binaries
      working-directory: ./Toolchain
      run: |
           ./download_rv32gc.sh
           ./download_rv32gcp.sh
           ./download_rv32gcv.sh
           ./download_rv32imv.sh
           ./download_llvm.sh 18
