name: Integration Tests

on:

  schedule:
    # 6am UTC is 7am Central European Time (CET) or 8am Central European Summer Time (CEST).
    - cron: '0 6 * * *'
  push:
    branches:
      - 'master'
#      - 'sync'
  pull_request:
    branches: [ "master" ]

  workflow_call:
  workflow_dispatch:

jobs:

  TFLM_Built_In_Tests_with_Patch:
    strategy:
        fail-fast: false
        matrix:
          config:
            - {vext: "OFF", pext: "OFF", mode: "RELEASE", toolchain: "x86", arch: "native", vlen: 0, elen: 64, sim: "Native"}
            - {vext: "OFF", pext: "OFF", mode: "RELEASE", toolchain: "gcc", arch: "rv32gc", vlen: 0, elen: 64, sim: "Spike"}
            - {vext: "OFF", pext: "OFF", mode: "RELEASE", toolchain: "llvm", arch: "rv32gc", vlen: 0, elen: 64, sim: "Spike"}
            - {vext: "OFF", pext: "ON", mode: "RELEASE", toolchain: "gcc", arch: "rv32gcp", vlen: 0, elen: 64, sim: "Spike"}
            # - {vext: "ON", pext: "OFF", mode: "RELEASE", toolchain: "gcc", arch: "rv32gcv", vlen: 64, elen: 64, sim: "Spike"}
            # - {vext: "ON", pext: "OFF", mode: "RELEASE", toolchain: "llvm", arch: "rv32gcv", vlen: 64, elen: 64, sim: "Spike"}
            - {vext: "ON", pext: "OFF", mode: "RELEASE", toolchain: "gcc", arch: "rv32gcv", vlen: 128, elen: 64, sim: "Spike"}
            - {vext: "ON", pext: "OFF", mode: "RELEASE", toolchain: "llvm", arch: "rv32gcv", vlen: 128, elen: 64, sim: "Spike"}
            - {vext: "ON", pext: "OFF", mode: "RELEASE", toolchain: "gcc", arch: "rv32gcv", vlen: 512, elen: 64, sim: "Spike"}
            - {vext: "ON", pext: "OFF", mode: "RELEASE", toolchain: "llvm", arch: "rv32gcv", vlen: 512, elen: 64, sim: "Spike"}

    name: TFLM Built-In Tests
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Install TFLM dependencies
      run: |
        sudo apt-get install python3-setuptools
        pip3 install wheel
        pip3 install Pillow
        pip3 install Wave
        pip3 install numpy

    - name: Get dates
      id: dates
      run: |
        echo "::set-output name=today::$(date +'%Y-%m-%d')"
        echo "::set-output name=yesterday::$(date +'%Y-%m-%d' -d yesterday)"
        echo "::set-output name=date::$(date +'%Y-%m-%d' -d 'last saturday')"

    - name: Download Cached GCC + LLVM Binaries
      if: ${{ matrix.config.toolchain }} != "x86"
      id: cache-gcc
      uses: actions/cache@v4
      env:
          cache-name: cache-gcc-binaries
      with:
          path: ./Toolchain
          key: gcc-binaries-${{ steps.dates.outputs.today }}
          restore-keys: |
            gcc-binaries-${{ steps.dates.outputs.yesterday }}
            gcc-binaries-${{ steps.dates.outputs.date }}
            gcc-binaries-

    - name: Install Spike Dependencies
      if: ${{ matrix.config.sim }} == "Spike"
      run: |
        sudo apt-get install libboost-all-dev
        sudo apt-get install device-tree-compiler

    - name: Download Spike Cache
      if: ${{ matrix.config.sim }} == "Spike"
      id: cache-Spike
      uses: actions/cache@v4
      env:
          cache-name: cache-spike-binaries
      with:
          path: ./Sim/Spike/bin
          key: spike-binaries-${{ steps.dates.outputs.today }}
          restore-keys: |
            spike-binaries-${{ steps.dates.outputs.yesterday }}
            spike-binaries-${{ steps.dates.outputs.date }}
            spike-binaries-

    - name: Download TFLM
      working-directory: ./Integration/TFLM
      run: git clone https://github.com/tensorflow/tflite-micro.git

    - name: Patch TFLM
      working-directory: ./Integration/TFLM/tflite-micro
      run: git apply ../muriscv_nn.patch

    - name: TFLM Integration Test for ${{ matrix.config.arch }} muRISCV-NN with ${{ matrix.config.toolchain }}, VLEN = ${{ matrix.config.vlen }}, SIM = ${{ matrix.config.sim }}
      working-directory: ./Integration/TFLM/tflite-micro
      run: ../tflm_integration_tests.sh ${{ matrix.config.vext }} ${{ matrix.config.pext }} ${{ matrix.config.mode }} ${{ matrix.config.toolchain }} ${{ matrix.config.arch }} ${{ matrix.config.vlen }} ${{ matrix.config.elen }} ${{ matrix.config.sim }}

  TVM_Integration_Tests:
    strategy:
        fail-fast: false
        matrix:
          config:
            - {vext_flag: "", pext_flag: "", toolchain: "x86", arch: "", vlen: 0, elen: 0, sim: "Native"}
            - {vext_flag: "", pext_flag: "", toolchain: "GCC", arch: "rv32gc", vlen: 0, elen: 0, sim: "Spike"}
            - {vext_flag: "", pext_flag: "", toolchain: "LLVM", arch: "rv32gc", vlen: 0, elen: 0, sim: "Spike"}
            - {vext_flag: "", pext_flag: "-p", toolchain: "GCC", arch: "rv32gcp", vlen: 0, elen: 0, sim: "Spike"}
            - {vext_flag: "-v", pext_flag: "", toolchain: "GCC", arch: "rv32gcv", vlen: 128, elen: 64, sim: "Spike"}
            - {vext_flag: "-v", pext_flag: "", toolchain: "LLVM", arch: "rv32gcv", vlen: 128, elen: 64, sim: "Spike"}
            - {vext_flag: "-v", pext_flag: "", toolchain: "GCC", arch: "rv32gcv", vlen: 512, elen: 64, sim: "Spike"}
            - {vext_flag: "-v", pext_flag: "", toolchain: "LLVM", arch: "rv32gcv", vlen: 512, elen: 64, sim: "Spike"}

    name: TVM Integration Tests
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Get dates
      id: dates
      run: |
        echo "::set-output name=today::$(date +'%Y-%m-%d')"
        echo "::set-output name=yesterday::$(date +'%Y-%m-%d' -d yesterday)"
        echo "::set-output name=date::$(date +'%Y-%m-%d' -d 'last saturday')"

    - name: Download Cached GCC + LLVM Binaries
      if: ${{ matrix.config.toolchain }} != "x86"
      id: cache-gcc
      uses: actions/cache@v4
      env:
          cache-name: cache-gcc-binaries
      with:
          path: ./Toolchain
          key: gcc-binaries-${{ steps.dates.outputs.today }}
          restore-keys: |
            gcc-binaries-${{ steps.dates.outputs.yesterday }}
            gcc-binaries-${{ steps.dates.outputs.date }}
            gcc-binaries-

    - name: Install Spike Dependencies
      if: ${{ matrix.config.sim }} == "Spike"
      run: |
        sudo apt-get install libboost-all-dev
        sudo apt-get install device-tree-compiler

    - name: Download Spike Cache
      if: ${{ matrix.config.sim }} == "Spike"
      id: cache-Spike
      uses: actions/cache@v4
      env:
          cache-name: cache-spike-binaries
      with:
          path: ./Sim/Spike/bin
          key: spike-binaries-${{ steps.dates.outputs.today }}
          restore-keys: |
            spike-binaries-${{ steps.dates.outputs.yesterday }}
            spike-binaries-${{ steps.dates.outputs.date }}
            spike-binaries-


    - name: TVM Integration Test AWW for ${{ matrix.config.arch }} muRISCV-NN with ${{ matrix.config.toolchain }}, VLEN = ${{ matrix.config.vlen }}, ELEN = ${{ matrix.config.elen }}, SIM = ${{ matrix.config.sim }}
      working-directory: ./Integration/tvm
      if: '!cancelled()'
      run: ./run_tvm_integration_tests.sh ${{ matrix.config.vext_flag }} ${{ matrix.config.pext_flag }} -t ${{ matrix.config.toolchain }} -l ${{ matrix.config.vlen }} -e ${{ matrix.config.elen }} -s ${{ matrix.config.sim }} -b aww

    - name: TVM Integration Test VWW for ${{ matrix.config.arch }} muRISCV-NN with ${{ matrix.config.toolchain }}, VLEN = ${{ matrix.config.vlen }}, ELEN = ${{ matrix.config.elen }}, SIM = ${{ matrix.config.sim }}
      working-directory: ./Integration/tvm
      if: '!cancelled()'
      run: ./run_tvm_integration_tests.sh ${{ matrix.config.vext_flag }} ${{ matrix.config.pext_flag }} -t ${{ matrix.config.toolchain }} -l ${{ matrix.config.vlen }} -e ${{ matrix.config.elen }} -s ${{ matrix.config.sim }} -b vww -S

    - name: TVM Integration Test RESNET for ${{ matrix.config.arch }} muRISCV-NN with ${{ matrix.config.toolchain }}, VLEN = ${{ matrix.config.vlen }}, ELEN = ${{ matrix.config.elen }}, SIM = ${{ matrix.config.sim }}
      working-directory: ./Integration/tvm
      if: '!cancelled()'
      run: ./run_tvm_integration_tests.sh ${{ matrix.config.vext_flag }} ${{ matrix.config.pext_flag }} -t ${{ matrix.config.toolchain }} -l ${{ matrix.config.vlen }} -e ${{ matrix.config.elen }} -s ${{ matrix.config.sim }} -b ic -S

    - name: TVM Integration Test TOYCAR for ${{ matrix.config.arch }} muRISCV-NN with ${{ matrix.config.toolchain }}, VLEN = ${{ matrix.config.vlen }}, ELEN = ${{ matrix.config.elen }}, SIM = ${{ matrix.config.sim }}
      working-directory: ./Integration/tvm
      if: '!cancelled()'
      run: ./run_tvm_integration_tests.sh ${{ matrix.config.vext_flag }} ${{ matrix.config.pext_flag }} -t ${{ matrix.config.toolchain }} -l ${{ matrix.config.vlen }} -e ${{ matrix.config.elen }} -s ${{ matrix.config.sim }} -b toy -S


  TFLM_Integration_Tests_Spike:
    strategy:
        fail-fast: false
        matrix:
          config:
            - {vext_flag: "", pext_flag: "", toolchain: "x86", arch: "", vlen: 0, elen: 0, sim: "Native"}
            - {vext_flag: "", pext_flag: "", toolchain: "GCC", arch: "rv32gc", vlen: 0, elen: 0, sim: "Spike"}
            - {vext_flag: "", pext_flag: "", toolchain: "LLVM", arch: "rv32gc", vlen: 0, elen: 0, sim: "Spike"}
            - {vext_flag: "", pext_flag: "-p", toolchain: "GCC", arch: "rv32gcp", vlen: 0, elen: 0, sim: "Spike"}
            - {vext_flag: "-v", pext_flag: "", toolchain: "GCC", arch: "rv32gcv", vlen: 128, elen: 64, sim: "Spike"}
            - {vext_flag: "-v", pext_flag: "", toolchain: "LLVM", arch: "rv32gcv", vlen: 128, elen: 64, sim: "Spike"}
            - {vext_flag: "-v", pext_flag: "", toolchain: "GCC", arch: "rv32gcv", vlen: 512, elen: 64, sim: "Spike"}
            - {vext_flag: "-v", pext_flag: "", toolchain: "LLVM", arch: "rv32gcv", vlen: 512, elen: 64, sim: "Spike"}

    name: TFLM Integration Tests
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Get dates
      id: dates
      run: |
        echo "::set-output name=today::$(date +'%Y-%m-%d')"
        echo "::set-output name=yesterday::$(date +'%Y-%m-%d' -d yesterday)"
        echo "::set-output name=date::$(date +'%Y-%m-%d' -d 'last saturday')"

    - name: Download Cached GCC + LLVM Binaries
      if: ${{ matrix.config.toolchain }} != "x86"
      id: cache-gcc
      uses: actions/cache@v4
      env:
          cache-name: cache-gcc-binaries
      with:
          path: ./Toolchain
          key: gcc-binaries-${{ steps.dates.outputs.today }}
          restore-keys: |
            gcc-binaries-${{ steps.dates.outputs.yesterday }}
            gcc-binaries-${{ steps.dates.outputs.date }}
            gcc-binaries-

    - name: Install Spike Dependencies
      if: ${{ matrix.config.sim }} == "Spike"
      run: |
        sudo apt-get install libboost-all-dev
        sudo apt-get install device-tree-compiler

    - name: Download Spike Cache
      if: ${{ matrix.config.sim }} == "Spike"
      id: cache-Spike
      uses: actions/cache@v4
      env:
          cache-name: cache-spike-binaries
      with:
          path: ./Sim/Spike/bin
          key: spike-binaries-${{ steps.dates.outputs.today }}
          restore-keys: |
            spike-binaries-${{ steps.dates.outputs.yesterday }}
            spike-binaries-${{ steps.dates.outputs.date }}
            spike-binaries-


    - name: Install TFLM dependencies
      run: |
        sudo apt-get install python3-setuptools
        pip3 install wheel
        pip3 install Pillow
        pip3 install Wave
        pip3 install numpy

    - name: Download TFLM and build Source Tree
      working-directory: ./Integration/tflm
      run: ./download_tflm.sh

    - name: TFLM Integration Test AWW for ${{ matrix.config.arch }} muRISCV-NN with ${{ matrix.config.toolchain }} with Spike, VLEN = ${{ matrix.config.vlen }}, ELEN = ${{ matrix.config.elen }}, SIM = ${{ matrix.config.sim }}
      working-directory: ./Integration/tflm
      if: '!cancelled()'
      run: ./run_tflm_integration_tests.sh ${{ matrix.config.vext_flag }} ${{ matrix.config.pext_flag }} -t ${{ matrix.config.toolchain }} -l ${{ matrix.config.vlen }} -e ${{ matrix.config.elen }} -s ${{ matrix.config.sim }} -b aww

    - name: TFLM Integration Test VWW for ${{ matrix.config.arch }} muRISCV-NN with ${{ matrix.config.toolchain }} with Spike, VLEN = ${{ matrix.config.vlen }}, ELEN = ${{ matrix.config.elen }}, SIM = ${{ matrix.config.sim }}
      working-directory: ./Integration/tflm
      if: '!cancelled()'
      run: ./run_tflm_integration_tests.sh ${{ matrix.config.vext_flag }} ${{ matrix.config.pext_flag }} -t ${{ matrix.config.toolchain }} -l ${{ matrix.config.vlen }} -e ${{ matrix.config.elen }} -s ${{ matrix.config.sim }} -b vww -S

    - name: TFLM Integration Test RESNET for ${{ matrix.config.arch }} muRISCV-NN with ${{ matrix.config.toolchain }} with Spike, VLEN = ${{ matrix.config.vlen }}, ELEN = ${{ matrix.config.elen }}, SIM = ${{ matrix.config.sim }}
      working-directory: ./Integration/tflm
      if: '!cancelled()'
      run: ./run_tflm_integration_tests.sh ${{ matrix.config.vext_flag }} ${{ matrix.config.pext_flag }} -t ${{ matrix.config.toolchain }} -l ${{ matrix.config.vlen }} -e ${{ matrix.config.elen }} -s ${{ matrix.config.sim }} -b ic -S

    - name: TFLM Integration Test TOYCAR for ${{ matrix.config.arch }} muRISCV-NN with ${{ matrix.config.toolchain }} with Spike, VLEN = ${{ matrix.config.vlen }}, ELEN = ${{ matrix.config.elen }}, SIM = ${{ matrix.config.sim }}
      working-directory: ./Integration/tflm
      if: '!cancelled()'
      run: ./run_tflm_integration_tests.sh ${{ matrix.config.vext_flag }} ${{ matrix.config.pext_flag }} -t ${{ matrix.config.toolchain }} -l ${{ matrix.config.vlen }} -e ${{ matrix.config.elen }} -s ${{ matrix.config.sim }} -b toy -S
